<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#단독다가구(one_two_room)" data-toc-modified-id="단독다가구(one_two_room)-1">단독다가구(one_two_room)</a></span></li><li><span><a href="#연립(villa)" data-toc-modified-id="연립(villa)-2">연립(villa)</a></span></li><li><span><a href="#오피스텔(officetels)" data-toc-modified-id="오피스텔(officetels)-3">오피스텔(officetels)</a></span></li></ul></div>

In [7]:
대형마트 = pd.read_csv('편의시설/300m내_대형마트(중복제거).csv')
print(대형마트.shape)
대형마트.head()

(27536, 8)


경도         위도              장소명           도로명     편의시설_경도  \
0  127.060991  37.483899  GS수퍼마켓 개포블레스티지점  서울 강남구 선릉로 8  127.062217   
1  127.060694  37.484075  GS수퍼마켓 개포블레스티지점  서울 강남구 선릉로 8  127.062217   
2  127.061118  37.483602  GS수퍼마켓 개포블레스티지점  서울 강남구 선릉로 8  127.062217   
3  127.061983  37.483285  GS수퍼마켓 개포블레스티지점  서울 강남구 선릉로 8  127.062217   
4  127.060078  37.483999  GS수퍼마켓 개포블레스티지점  서울 강남구 선릉로 8  127.062217   

     편의시설_위도   주택형태                                  기준  
0  37.482159  단독다가구    37.4838993527963127.060991290466  
1  37.482159  단독다가구    37.4840747521106127.060693844398  
2  37.482159  단독다가구  37.4836015938737127.06111847254499  
3  37.482159  단독다가구  37.4832847996201127.06198259187599  
4  37.482159  단독다가구  37.4839988417672127.06007757611201

In [8]:
패스트푸드 = pd.read_csv('편의시설/300m내_패스트푸드(중복제거).csv')
print(패스트푸드.shape)
패스트푸드.head()

(23474, 8)


경도         위도          장소명            도로명     편의시설_경도    편의시설_위도  \
0  127.060991  37.483899     롯데리아 개포점  서울 강남구 선릉로 26  127.061465  37.482201   
1  127.060694  37.484075     롯데리아 개포점  서울 강남구 선릉로 26  127.061465  37.482201   
2  127.045229  37.479780  써브웨이 포이사거리점  서울 강남구 논현로 84  127.045263  37.477526   
3  127.046581  37.479855  써브웨이 포이사거리점  서울 강남구 논현로 84  127.045263  37.477526   
4  127.045831  37.478206  써브웨이 포이사거리점  서울 강남구 논현로 84  127.045263  37.477526   

    주택형태                                    기준  
0  단독다가구      37.4838993527963127.060991290466  
1  단독다가구      37.4840747521106127.060693844398  
2  단독다가구  37.479780087904295127.04522930859699  
3  단독다가구      37.4798545267632127.046580863676  
4  단독다가구    37.4782063336653127.04583050040199

## 단독다가구(one_two_room)

In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

In [4]:
단독다가구 = pd.read_csv('data/one_two_room.csv', thousands=',', index_col=0)
print(단독다가구.shape)
단독다가구

(688663, 17)


address rent    size  deposit  pay    year    contract  \
0           서울특별시 강남구 개포동 개포로   월세   26.00     1000   80  1988.0  2016-04-20   
1           서울특별시 강남구 개포동 개포로   전세  100.00    24000    0  1988.0  2016-07-25   
2           서울특별시 강남구 개포동 개포로   전세  100.00    25500    0  1988.0  2018-05-06   
3           서울특별시 강남구 개포동 개포로   전세   32.44    13000    0     NaN  2015-12-17   
4           서울특별시 강남구 개포동 개포로   전세   32.44    14500    0     NaN  2018-12-10   
...                       ...  ...     ...      ...  ...     ...         ...   
688658  서울특별시 중랑구 중화동 중랑천로36길   전세   43.11     9000    0  1989.0  2016-09-23   
688659  서울특별시 중랑구 중화동 중랑천로36길   전세   47.68    13000    0  1993.0  2020-02-06   
688660  서울특별시 중랑구 중화동 중랑천로36길   전세   48.19     6000    0  1993.0  2019-09-01   
688661  서울특별시 중랑구 중화동 중랑천로36길   전세   50.29    14000    0  1993.0  2020-02-18   
688662  서울특별시 중랑구 중화동 중랑천로36길   전세   70.98    14500    0  2018.0  2018-11-02   

           road area  recent   latitude   longitude  station_area  \
0           개포로  강남구       1  37.476873  127.050971             0   
1           개포로  강남구       0  37.476873  127.050971             0   
2           개포로  강남구       1  37.476873  127.050971             0   
3           개포로  강남구       0  37.476873  127.050971             0   
4           개포로  강남구       1  37.476873  127.050971             0   
...         ...  ...     ...        ...         ...           ...   
688658  중랑천로36길  중랑구       1  37.600814  127.074633             1   
688659  중랑천로36길  중랑구       1  37.600814  127.074633             1   
688660  중랑천로36길  중랑구       1  37.600814  127.074633             1   
688661  중랑천로36길  중랑구       1  37.600814  127.074633             1   
688662  중랑천로36길  중랑구       1  37.600814  127.074633             1   

       station_name  transfer                            criteria  hos_num  
0                []         0  37.476873436935705127.050971077409      1.0  
1                []         0  37.476873436935705127.050971077409      1.0  
2                []         0  37.476873436935705127.050971077409      1.0  
3                []         0  37.476873436935705127.050971077409      1.0  
4                []         0  37.476873436935705127.050971077409      1.0  
...             ...       ...                                 ...      ...  
688658  ['중화역 7호선']         0  37.6008138615665127.07463250319599      0.0  
688659  ['중화역 7호선']         0  37.6008138615665127.07463250319599      0.0  
688660  ['중화역 7호선']         0  37.6008138615665127.07463250319599      0.0  
688661  ['중화역 7호선']         0  37.6008138615665127.07463250319599      0.0  
688662  ['중화역 7호선']         0  37.6008138615665127.07463250319599      0.0  

[688663 rows x 17 columns]

In [10]:
mart_group = 대형마트.groupby(['기준'])['장소명'].count().reset_index().sort_values(by='장소명')
mart_group.columns = ['criteria','mart_num']
mart_group

criteria  mart_num
0        33.2480661563758126.56068077601101         1
15156     37.560609415794794126.92776608678         1
15155    37.5606069839045127.03947340108299         1
15154     37.56060364767461126.927616127346         1
15153      37.5606030082784127.031406412435         1
...                                     ...       ...
15941        37.57038662514126.840244784286         6
15952   37.57060341173121126.84011708874701         6
18275      37.5960052612377127.087261864983         6
15850   37.56859908881621126.84275537747101         6
15970  37.570835587390704126.84037558608699         6

[23610 rows x 2 columns]

In [30]:
fast_group = 패스트푸드.groupby(['기준'])['장소명'].count().reset_index().sort_values(by='장소명')
fast_group.columns = ['criteria','fast_num']
fast_group

criteria  fast_num
0          33.5061298401656126.539246511365         1
9896       37.5432066246139126.840379065572         1
9897       37.5432155959501126.964930025938         1
9898       37.5432203816097126.835500255779         1
9899   37.543229613619296126.83663370679899         1
...                                     ...       ...
15309    37.6021824467851127.08042245533599         6
16328      37.6110328822877126.915473190131         6
57         35.8535169765623128.549377052773         6
16451      37.6114977979985126.915480818535         6
16746     37.61393199276971126.929610657786         8

[18534 rows x 2 columns]

In [44]:
단독다가구2 = pd.merge(단독다가구, mart_group, on='criteria', how='left')
단독다가구3 = pd.merge(단독다가구2, fast_group, on='criteria', how='left')

In [53]:
print(단독다가구3['mart_num'].unique())
print(단독다가구3['fast_num'].unique())

[0. 3. 1. 2. 4.]
[0. 2. 1. 4. 3. 6. 8. 5.]


In [54]:
print(단독다가구3['mart_num'].value_counts())
print(단독다가구3['fast_num'].value_counts())

0.0    513389
1.0    139479
2.0     31685
4.0      2272
3.0      1838
Name: mart_num, dtype: int64
0.0    554342
1.0     96368
2.0     32116
3.0      3291
4.0      1905
6.0       341
5.0       218
8.0        82
Name: fast_num, dtype: int64


In [48]:
단독다가구3.head()

address rent    size  deposit  pay    year    contract road area  \
0  서울특별시 강남구 개포동 개포로   월세   26.00     1000   80  1988.0  2016-04-20  개포로  강남구   
1  서울특별시 강남구 개포동 개포로   전세  100.00    24000    0  1988.0  2016-07-25  개포로  강남구   
2  서울특별시 강남구 개포동 개포로   전세  100.00    25500    0  1988.0  2018-05-06  개포로  강남구   
3  서울특별시 강남구 개포동 개포로   전세   32.44    13000    0     NaN  2015-12-17  개포로  강남구   
4  서울특별시 강남구 개포동 개포로   전세   32.44    14500    0     NaN  2018-12-10  개포로  강남구   

   recent   latitude   longitude  station_area station_name  transfer  \
0       1  37.476873  127.050971             0           []         0   
1       0  37.476873  127.050971             0           []         0   
2       1  37.476873  127.050971             0           []         0   
3       0  37.476873  127.050971             0           []         0   
4       1  37.476873  127.050971             0           []         0   

                             criteria  hos_num  mart_num  fast_num  
0  37.476873436935705127.050971077409      1.0       NaN       NaN  
1  37.476873436935705127.050971077409      1.0       NaN       NaN  
2  37.476873436935705127.050971077409      1.0       NaN       NaN  
3  37.476873436935705127.050971077409      1.0       NaN       NaN  
4  37.476873436935705127.050971077409      1.0       NaN       NaN

In [51]:
단독다가구3['mart_num'] = 단독다가구3['mart_num'].fillna(0)
단독다가구3['fast_num'] = 단독다가구3['fast_num'].fillna(0)

In [52]:
단독다가구3.head()

address rent    size  deposit  pay    year    contract road area  \
0  서울특별시 강남구 개포동 개포로   월세   26.00     1000   80  1988.0  2016-04-20  개포로  강남구   
1  서울특별시 강남구 개포동 개포로   전세  100.00    24000    0  1988.0  2016-07-25  개포로  강남구   
2  서울특별시 강남구 개포동 개포로   전세  100.00    25500    0  1988.0  2018-05-06  개포로  강남구   
3  서울특별시 강남구 개포동 개포로   전세   32.44    13000    0     NaN  2015-12-17  개포로  강남구   
4  서울특별시 강남구 개포동 개포로   전세   32.44    14500    0     NaN  2018-12-10  개포로  강남구   

   recent   latitude   longitude  station_area station_name  transfer  \
0       1  37.476873  127.050971             0           []         0   
1       0  37.476873  127.050971             0           []         0   
2       1  37.476873  127.050971             0           []         0   
3       0  37.476873  127.050971             0           []         0   
4       1  37.476873  127.050971             0           []         0   

                             criteria  hos_num  mart_num  fast_num  
0  37.476873436935705127.050971077409      1.0       0.0       0.0  
1  37.476873436935705127.050971077409      1.0       0.0       0.0  
2  37.476873436935705127.050971077409      1.0       0.0       0.0  
3  37.476873436935705127.050971077409      1.0       0.0       0.0  
4  37.476873436935705127.050971077409      1.0       0.0       0.0

In [55]:
단독다가구3.to_csv('data/one_two_room.csv', encoding='utf-8', index=False)

## 연립(villa)

In [57]:
연립 = pd.read_csv('data/villa.csv', thousands=',', index_col=0)
print(연립.shape)
연립

(503838, 19)


address rent   size  deposit  pay    year  \
0                 서울특별시 강남구 개포동     월세  34.22     3000   30  2012.0   
1                 서울특별시 강남구 개포동     월세  39.34    10000   60  2015.0   
2                 서울특별시 강남구 개포동     월세  48.50     3000   53  1988.0   
3                 서울특별시 강남구 개포동     월세  48.50    10000   40  1988.0   
4                 서울특별시 강남구 개포동     월세  53.99    28000   20  2013.0   
...                           ...  ...    ...      ...  ...     ...   
503833  서울특별시 중랑구 중화동 중랑천로36길 5-4   전세  34.98    11000    0  1997.0   
503834  서울특별시 중랑구 중화동 중랑천로36길 5-4   전세  36.54    10000    0  1997.0   
503835  서울특별시 중랑구 중화동 중랑천로36길 5-4   전세  42.18    12000    0  1997.0   
503836  서울특별시 중랑구 중화동 중랑천로36길 5-4   전세  42.18    13000    0  1997.0   
503837  서울특별시 중랑구 중화동 중랑천로36길 5-4   전세  42.18    13000    0  1997.0   

          contract         road    name  floor area  recent   latitude  \
0       2015-10-14                아름다운집    NaN  강남구       0  37.548566   
1       2015-09-02               수창스마트빌    2.0  강남구       1  37.548566   
2       2015-08-17                  영동A    0.0  강남구       1  37.548566   
3       2016-01-21                  영동B    1.0  강남구       1  37.548566   
4       2016-02-19                   장원    5.0  강남구       1  37.548566   
...            ...          ...     ...    ...  ...     ...        ...   
503833  2018-03-31  중랑천로36길 5-4    진주빌라    1.0  중랑구       1  37.601040   
503834  2016-09-24  중랑천로36길 5-4    진주빌라    3.0  중랑구       1  37.601040   
503835  2018-03-23  중랑천로36길 5-4    진주빌라    3.0  중랑구       0  37.601040   
503836  2018-11-17  중랑천로36길 5-4    진주빌라    3.0  중랑구       0  37.601040   
503837  2019-01-31  중랑천로36길 5-4    진주빌라    3.0  중랑구       1  37.601040   

         longitude  station_area station_name  transfer  \
0       127.130212             2  ['암사역 8호선']         0   
1       127.130212             2  ['암사역 8호선']         0   
2       127.130212             2  ['암사역 8호선']         0   
3       127.130212             2  ['암사역 8호선']         0   
4       127.130212             2  ['암사역 8호선']         0   
...            ...           ...          ...       ...   
503833  127.074723             1  ['중화역 7호선']         0   
503834  127.074723             1  ['중화역 7호선']         0   
503835  127.074723             1  ['중화역 7호선']         0   
503836  127.074723             1  ['중화역 7호선']         0   
503837  127.074723             1  ['중화역 7호선']         0   

                                  criteria  hos_num  
0       37.548566265313895127.130212056093      2.0  
1       37.548566265313895127.130212056093      2.0  
2       37.548566265313895127.130212056093      2.0  
3       37.548566265313895127.130212056093      2.0  
4       37.548566265313895127.130212056093      2.0  
...                                    ...      ...  
503833      37.6010403136118127.0747225306      2.0  
503834      37.6010403136118127.0747225306      2.0  
503835      37.6010403136118127.0747225306      2.0  
503836      37.6010403136118127.0747225306      2.0  
503837      37.6010403136118127.0747225306      2.0  

[503838 rows x 19 columns]

In [58]:
mart_group

criteria  mart_num
0        33.2480661563758126.56068077601101         1
15156     37.560609415794794126.92776608678         1
15155    37.5606069839045127.03947340108299         1
15154     37.56060364767461126.927616127346         1
15153      37.5606030082784127.031406412435         1
...                                     ...       ...
15941        37.57038662514126.840244784286         6
15952   37.57060341173121126.84011708874701         6
18275      37.5960052612377127.087261864983         6
15850   37.56859908881621126.84275537747101         6
15970  37.570835587390704126.84037558608699         6

[23610 rows x 2 columns]

In [59]:
fast_group

criteria  fast_num
0          33.5061298401656126.539246511365         1
9896       37.5432066246139126.840379065572         1
9897       37.5432155959501126.964930025938         1
9898       37.5432203816097126.835500255779         1
9899   37.543229613619296126.83663370679899         1
...                                     ...       ...
15309    37.6021824467851127.08042245533599         6
16328      37.6110328822877126.915473190131         6
57         35.8535169765623128.549377052773         6
16451      37.6114977979985126.915480818535         6
16746     37.61393199276971126.929610657786         8

[18534 rows x 2 columns]

In [60]:
연립2 = pd.merge(연립, mart_group, on='criteria', how='left')
연립3 = pd.merge(연립2, fast_group, on='criteria', how='left')

In [66]:
print(연립3['mart_num'].unique())
print(연립3['fast_num'].unique())

[0. 1. 2. 3. 4. 6.]
[0. 2. 1. 4. 3. 6. 5. 8.]


In [67]:
print(연립3['mart_num'].value_counts())
print(연립3['fast_num'].value_counts())

0.0    377688
1.0    103619
2.0     20579
3.0      1009
4.0       817
6.0       126
Name: mart_num, dtype: int64
0.0    403330
1.0     77854
2.0     19489
3.0      2212
4.0       845
6.0        90
5.0        17
8.0         1
Name: fast_num, dtype: int64


In [63]:
연립3.head()

address rent   size  deposit  pay    year    contract road    name  \
0  서울특별시 강남구 개포동     월세  34.22     3000   30  2012.0  2015-10-14        아름다운집   
1  서울특별시 강남구 개포동     월세  39.34    10000   60  2015.0  2015-09-02       수창스마트빌   
2  서울특별시 강남구 개포동     월세  48.50     3000   53  1988.0  2015-08-17          영동A   
3  서울특별시 강남구 개포동     월세  48.50    10000   40  1988.0  2016-01-21          영동B   
4  서울특별시 강남구 개포동     월세  53.99    28000   20  2013.0  2016-02-19           장원   

   floor  ... recent   latitude   longitude  station_area  station_name  \
0    NaN  ...      0  37.548566  127.130212             2   ['암사역 8호선']   
1    2.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
2    0.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
3    1.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
4    5.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   

  transfer                            criteria hos_num  mart_num  fast_num  
0        0  37.548566265313895127.130212056093     2.0       NaN       NaN  
1        0  37.548566265313895127.130212056093     2.0       NaN       NaN  
2        0  37.548566265313895127.130212056093     2.0       NaN       NaN  
3        0  37.548566265313895127.130212056093     2.0       NaN       NaN  
4        0  37.548566265313895127.130212056093     2.0       NaN       NaN  

[5 rows x 21 columns]

In [64]:
연립3['mart_num'] = 연립3['mart_num'].fillna(0)
연립3['fast_num'] = 연립3['fast_num'].fillna(0)

In [65]:
연립3.head()

address rent   size  deposit  pay    year    contract road    name  \
0  서울특별시 강남구 개포동     월세  34.22     3000   30  2012.0  2015-10-14        아름다운집   
1  서울특별시 강남구 개포동     월세  39.34    10000   60  2015.0  2015-09-02       수창스마트빌   
2  서울특별시 강남구 개포동     월세  48.50     3000   53  1988.0  2015-08-17          영동A   
3  서울특별시 강남구 개포동     월세  48.50    10000   40  1988.0  2016-01-21          영동B   
4  서울특별시 강남구 개포동     월세  53.99    28000   20  2013.0  2016-02-19           장원   

   floor  ... recent   latitude   longitude  station_area  station_name  \
0    NaN  ...      0  37.548566  127.130212             2   ['암사역 8호선']   
1    2.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
2    0.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
3    1.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   
4    5.0  ...      1  37.548566  127.130212             2   ['암사역 8호선']   

  transfer                            criteria hos_num  mart_num  fast_num  
0        0  37.548566265313895127.130212056093     2.0       0.0       0.0  
1        0  37.548566265313895127.130212056093     2.0       0.0       0.0  
2        0  37.548566265313895127.130212056093     2.0       0.0       0.0  
3        0  37.548566265313895127.130212056093     2.0       0.0       0.0  
4        0  37.548566265313895127.130212056093     2.0       0.0       0.0  

[5 rows x 21 columns]

In [68]:
연립3.to_csv('data/villa.csv', encoding='utf-8', index=False)

## 오피스텔(officetels)

In [69]:
오피스텔 = pd.read_csv('data/officetels.csv', thousands=',', index_col=0)
print(오피스텔.shape)
오피스텔

(208947, 19)


address rent   size  deposit  pay    year  \
0          서울특별시 강남구 개포동 개포로 213   월세  18.80      200   75  2003.0   
1          서울특별시 강남구 개포동 개포로 213   월세  18.80      100   70  2003.0   
2          서울특별시 강남구 개포동 개포로 213   월세  19.08      200   75  2003.0   
3          서울특별시 강남구 개포동 개포로 213   월세  23.76      100   80  2003.0   
4          서울특별시 강남구 개포동 개포로 213   월세  23.76     1000   80  2003.0   
...                          ...  ...    ...      ...  ...     ...   
208942  서울특별시 중랑구 중화동 중랑천로14길 58   전세  22.21    10500    0  2012.0   
208943  서울특별시 중랑구 중화동 중랑천로14길 58   전세  22.21    10000    0  2012.0   
208944  서울특별시 중랑구 중화동 중랑천로14길 58   전세  22.21    12000    0  2012.0   
208945  서울특별시 중랑구 중화동 중랑천로14길 58   전세  22.21    11000    0  2012.0   
208946  서울특별시 중랑구 중화동 중랑천로14길 58   전세  22.21    12000    0  2012.0   

          contract        road             name  floor area  recent  \
0       2015-02-02     개포로 213  골든빌오피스텔(1246-3)      2  강남구       1   
1       2017-06-10     개포로 213  골든빌오피스텔(1246-3)      6  강남구       1   
2       2015-01-05     개포로 213  골든빌오피스텔(1246-3)      2  강남구       1   
3       2015-08-20     개포로 213  골든빌오피스텔(1246-3)      4  강남구       1   
4       2020-07-10     개포로 213  골든빌오피스텔(1246-3)      2  강남구       1   
...            ...         ...              ...    ...  ...     ...   
208942  2020-03-11  중랑천로14길 58        중화동 범양프레체      6  중랑구       0   
208943  2020-04-11  중랑천로14길 58        중화동 범양프레체      3  중랑구       1   
208944  2020-04-20  중랑천로14길 58        중화동 범양프레체      6  중랑구       0   
208945  2020-04-29  중랑천로14길 58        중화동 범양프레체      2  중랑구       1   
208946  2020-04-30  중랑천로14길 58        중화동 범양프레체      6  중랑구       1   

         latitude   longitude  station_area           station_name  transfer  \
0       37.478745  127.046113             0                     []         0   
1       37.478745  127.046113             0                     []         0   
2       37.478745  127.046113             0                     []         0   
3       37.478745  127.046113             0                     []         0   
4       37.478745  127.046113             0                     []         0   
...           ...         ...           ...                    ...       ...   
208942  37.594532  127.075918             2  ['중랑역 경의선' '중랑역 경춘선']         1   
208943  37.594532  127.075918             2  ['중랑역 경의선' '중랑역 경춘선']         1   
208944  37.594532  127.075918             2  ['중랑역 경의선' '중랑역 경춘선']         1   
208945  37.594532  127.075918             2  ['중랑역 경의선' '중랑역 경춘선']         1   
208946  37.594532  127.075918             2  ['중랑역 경의선' '중랑역 경춘선']         1   

                                criteria  hos_num  
0       37.4787447572028127.046112568695      3.0  
1       37.4787447572028127.046112568695      3.0  
2       37.4787447572028127.046112568695      3.0  
3       37.4787447572028127.046112568695      3.0  
4       37.4787447572028127.046112568695      3.0  
...                                  ...      ...  
208942  37.5945315127732127.075917984894      8.0  
208943  37.5945315127732127.075917984894      8.0  
208944  37.5945315127732127.075917984894      8.0  
208945  37.5945315127732127.075917984894      8.0  
208946  37.5945315127732127.075917984894      8.0  

[208947 rows x 19 columns]

In [70]:
mart_group

criteria  mart_num
0        33.2480661563758126.56068077601101         1
15156     37.560609415794794126.92776608678         1
15155    37.5606069839045127.03947340108299         1
15154     37.56060364767461126.927616127346         1
15153      37.5606030082784127.031406412435         1
...                                     ...       ...
15941        37.57038662514126.840244784286         6
15952   37.57060341173121126.84011708874701         6
18275      37.5960052612377127.087261864983         6
15850   37.56859908881621126.84275537747101         6
15970  37.570835587390704126.84037558608699         6

[23610 rows x 2 columns]

In [71]:
fast_group

criteria  fast_num
0          33.5061298401656126.539246511365         1
9896       37.5432066246139126.840379065572         1
9897       37.5432155959501126.964930025938         1
9898       37.5432203816097126.835500255779         1
9899   37.543229613619296126.83663370679899         1
...                                     ...       ...
15309    37.6021824467851127.08042245533599         6
16328      37.6110328822877126.915473190131         6
57         35.8535169765623128.549377052773         6
16451      37.6114977979985126.915480818535         6
16746     37.61393199276971126.929610657786         8

[18534 rows x 2 columns]

In [72]:
오피스텔2 = pd.merge(오피스텔, mart_group, on='criteria', how='left')
오피스텔3 = pd.merge(오피스텔2, fast_group, on='criteria', how='left')

In [79]:
print(오피스텔3['mart_num'].unique())
print(오피스텔3['fast_num'].unique())

[0. 1. 2. 3. 4. 6.]
[1. 0. 2. 3. 4. 6. 5.]


In [80]:
print(오피스텔3['mart_num'].value_counts())
print(오피스텔3['fast_num'].value_counts())

0.0    136163
1.0     50634
2.0     17015
3.0      3673
4.0      1318
6.0       144
Name: mart_num, dtype: int64
0.0    121603
1.0     73044
2.0     12742
4.0       891
3.0       583
6.0        74
5.0        10
Name: fast_num, dtype: int64


In [76]:
오피스텔3.head()

address rent   size  deposit  pay    year    contract  \
0  서울특별시 강남구 개포동 개포로 213   월세  18.80      200   75  2003.0  2015-02-02   
1  서울특별시 강남구 개포동 개포로 213   월세  18.80      100   70  2003.0  2017-06-10   
2  서울특별시 강남구 개포동 개포로 213   월세  19.08      200   75  2003.0  2015-01-05   
3  서울특별시 강남구 개포동 개포로 213   월세  23.76      100   80  2003.0  2015-08-20   
4  서울특별시 강남구 개포동 개포로 213   월세  23.76     1000   80  2003.0  2020-07-10   

      road             name  floor  ... recent   latitude   longitude  \
0  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   
1  개포로 213  골든빌오피스텔(1246-3)      6  ...      1  37.478745  127.046113   
2  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   
3  개포로 213  골든빌오피스텔(1246-3)      4  ...      1  37.478745  127.046113   
4  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   

   station_area  station_name transfer                          criteria  \
0             0            []        0  37.4787447572028127.046112568695   
1             0            []        0  37.4787447572028127.046112568695   
2             0            []        0  37.4787447572028127.046112568695   
3             0            []        0  37.4787447572028127.046112568695   
4             0            []        0  37.4787447572028127.046112568695   

  hos_num  mart_num  fast_num  
0     3.0       NaN       1.0  
1     3.0       NaN       1.0  
2     3.0       NaN       1.0  
3     3.0       NaN       1.0  
4     3.0       NaN       1.0  

[5 rows x 21 columns]

In [77]:
오피스텔3['mart_num'] = 오피스텔3['mart_num'].fillna(0)
오피스텔3['fast_num'] = 오피스텔3['fast_num'].fillna(0)

In [78]:
오피스텔3.head()

address rent   size  deposit  pay    year    contract  \
0  서울특별시 강남구 개포동 개포로 213   월세  18.80      200   75  2003.0  2015-02-02   
1  서울특별시 강남구 개포동 개포로 213   월세  18.80      100   70  2003.0  2017-06-10   
2  서울특별시 강남구 개포동 개포로 213   월세  19.08      200   75  2003.0  2015-01-05   
3  서울특별시 강남구 개포동 개포로 213   월세  23.76      100   80  2003.0  2015-08-20   
4  서울특별시 강남구 개포동 개포로 213   월세  23.76     1000   80  2003.0  2020-07-10   

      road             name  floor  ... recent   latitude   longitude  \
0  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   
1  개포로 213  골든빌오피스텔(1246-3)      6  ...      1  37.478745  127.046113   
2  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   
3  개포로 213  골든빌오피스텔(1246-3)      4  ...      1  37.478745  127.046113   
4  개포로 213  골든빌오피스텔(1246-3)      2  ...      1  37.478745  127.046113   

   station_area  station_name transfer                          criteria  \
0             0            []        0  37.4787447572028127.046112568695   
1             0            []        0  37.4787447572028127.046112568695   
2             0            []        0  37.4787447572028127.046112568695   
3             0            []        0  37.4787447572028127.046112568695   
4             0            []        0  37.4787447572028127.046112568695   

  hos_num  mart_num  fast_num  
0     3.0       0.0       1.0  
1     3.0       0.0       1.0  
2     3.0       0.0       1.0  
3     3.0       0.0       1.0  
4     3.0       0.0       1.0  

[5 rows x 21 columns]

In [81]:
오피스텔3.to_csv('data/officetels.csv', encoding='utf-8', index=False)